# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release

on:
  push:
    tags:
      - v*

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: npm production
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install jupyter
    - name: Run the notebook
      run: |
        jupyter execute Convert.ipynb
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        npm version prerelease

        npm publish --access public
        git commit -a -m "Update version [skip ci]"


      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}