# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release

on:
  push:
    branches:
      - main
    paths: 
      - catCFDI_V_4_16112023.xls
      - Convert.ipynb

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install jupyter
    - name: Run the notebook
      run: |
        jupyter execute Convert.ipynb
    - run: |
        version=$(jq -r '.version' package.json)-build.${{  github.run_number }}-${{  github.run_attempt }}
        echo "version: $version"
        npm pkg set-version $version
        # Lets package the module
        npm pack
        # npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}